"""Turn research students already did into a DRAFT knowledge pack for the team to review.

cd backend && uv run python -m scripts.promote_research "Tata Capital Pankh" [--portal tatacapital]

Reads the research_cache row (quote-checked items only), writes knowledge/<portal>/<slug>.json with
status "draft", and validates it with the pack model. Every criterion has logic=null (shown as
"unknown" until a reviewer writes the rule) and each document's type is a guess: review both, add
mr/hi text, then set status "verified" with verified_by/verified_on. A verified pack is instant
for every student (no live research at all)."""

import argparse
import json
import re
import sys
from datetime import date

from app.agent.tools.research import cache_key
from app.db import supabase as repo
from app.research.packs import KNOWLEDGE, Pack

# The first match wins; anything else is "other" for the reviewer to fix.
DOC_GUESS = (
    (r"income", "income_certificate"),
    (r"validity", "caste_validity"),
    (r"caste", "caste_certificate"),
    (r"domicile|residence", "domicile_certificate"),
    (r"aadha?a?r", "aadhaar"),
    (r"\b(10th|ssc|class 10|matric)", "ssc_marksheet"),
    (r"\b(12th|hsc|class 12)", "hsc_marksheet"),
    (r"bank|passbook", "bank_passbook"),
    (r"fee", "fee_receipt"),
    (r"admission|bonafide", "admission_letter"),
    (r"gap", "gap_certificate"),
)


def doc_type(text: str) -> str:
    return next((t for rx, t in DOC_GUESS if re.search(rx, text, re.I)), "other")


def draft_pack(row: dict, portal: str) -> dict:
    items = row["items"]
    slug = re.sub(r"[^a-z0-9]+", "_", row["scheme_name"].lower()).strip("_")[:60]
    src = lambda it: {"url": it["source_url"], "quote": it["quote"]}  # noqa: E731
    elig, docs = items.get("eligibility", []), items.get("documents", [])
    urls = list(dict.fromkeys(it["source_url"] for it in [*elig, *docs]))
    return {
        "scheme_key": f"{portal}.{slug}",
        "portal": portal,
        "status": "draft",
        "name": {"en": row["scheme_name"]},
        "department": "",
        "official_urls": urls,
        "summary": {"en": f"Draft from live research ({str(row['saved_at'])[:10]}): review it."},
        "criteria": [
            {"id": f"live_{i + 1}", "text": {"en": it["text"]}, "logic": None, "source": src(it)}
            for i, it in enumerate(elig)
        ],
        "documents": [
            {
                "doc_type": doc_type(it["text"]),
                "required": True,
                "text": {"en": it["text"]},
                "source": src(it),
            }
            for it in docs
        ],
        "notes": [
            f"Generated by scripts/promote_research.py on {date.today()} from research_cache. "
            "Every criterion needs its rule (logic) and every doc_type is a guess: review before "
            "setting status to verified.",
        ],
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("scheme")
    ap.add_argument("--portal", default="other", help="knowledge/<portal>/ folder (a-z, 0-9, _)")
    args = ap.parse_args()
    key = cache_key(args.scheme)
    rows = repo.get_db().table("research_cache").select("*").eq("scheme_norm", key).execute().data
    if not rows:
        sys.exit(f"no research_cache row for {key!r}: research it once in the app first")
    pack = draft_pack(rows[0], args.portal)
    Pack.model_validate(pack)  # the same checks the app applies when it loads packs
    out = KNOWLEDGE / args.portal / f"{pack['scheme_key'].split('.', 1)[1]}.json"
    if out.exists():
        sys.exit(f"{out} exists: review or remove it first")
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(pack, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(pack['criteria'])} criteria, {len(pack['documents'])} documents)")
    if not (KNOWLEDGE / args.portal / "_portal.json").exists():
        print(f"note: add knowledge/{args.portal}/_portal.json (portal name + url) when reviewing")


if __name__ == "__main__":
    main()
