"""Turn research students already did into a DRAFT knowledge pack for the team to review.

cd backend && uv run python -m scripts.promote_research "Tata Capital Pankh" \
    [--portal tatacapital] [--cycle 2026-27]

Reads the research_cache row (quote-checked items only), writes knowledge/<portal>/<slug>.json with
status "draft", and validates it with the pack model. Every criterion has logic=null (shown as
"unknown" until a reviewer writes the rule) and each document's type is a guess: review both, add
mr/hi text, then set status "verified" with verified_by/verified_on. A verified pack is instant
for every student (no live research at all)."""

import argparse
import json
import re
import sys
from datetime import date

from app.agent.tools.research import cache_key
from app.db import supabase as repo
from app.research.packs import KNOWLEDGE, Pack, current_cycle
from app.verify.requirements import doc_type


def draft_pack(row: dict, portal: str) -> dict:
    items = row["items"]
    slug = re.sub(r"[^a-z0-9]+", "_", row["scheme_name"].lower()).strip("_")[:60]
    src = lambda it: {"url": it["source_url"], "quote": it["quote"]}  # noqa: E731
    elig, docs = items.get("eligibility", []), items.get("documents", [])
    urls = list(dict.fromkeys(it["source_url"] for it in [*elig, *docs]))
    return {
        "scheme_key": f"{portal}.{slug}",
        "portal": portal,
        "status": "draft",
        "name": {"en": row["scheme_name"]},
        "department": "",
        "official_urls": urls,
        "summary": {"en": f"Draft from live research ({str(row['saved_at'])[:10]}): review it."},
        "criteria": [
            {"id": f"live_{i + 1}", "text": {"en": it["text"]}, "logic": None, "source": src(it)}
            for i, it in enumerate(elig)
        ],
        "documents": [
            {
                "id": f"doc_{i + 1}",
                "doc_type": (it.get("doc_types") or [doc_type(it["text"])])[0],
                "required": it.get("required", "yes") != "optional",
                "text": {"en": it["text"]},
                "source": src(it),
            }
            for i, it in enumerate(docs)
        ],
        "notes": [
            f"Generated by scripts/promote_research.py on {date.today()} from research_cache. "
            "Every criterion needs its rule (logic) and every doc_type is a guess: review before "
            "setting status to verified.",
        ],
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("scheme")
    ap.add_argument("--portal", default="other", help="knowledge/<portal>/ folder (a-z, 0-9, _)")
    ap.add_argument("--cycle", default="", help="academic year, e.g. 2026-27 (default: current)")
    args = ap.parse_args()
    cycle = args.cycle or current_cycle()
    key = cache_key(args.scheme, cycle)
    rows = repo.get_db().table("research_cache").select("*").eq("scheme_norm", key).execute().data
    if not rows:
        sys.exit(f"no research_cache row for {key!r}: research it once in the app first")
    pack = draft_pack(rows[0], args.portal) | {"academic_year": cycle}
    Pack.model_validate(pack)  # the same checks the app applies when it loads packs
    out = KNOWLEDGE / args.portal / f"{pack['scheme_key'].split('.', 1)[1]}.json"
    if out.exists():
        sys.exit(f"{out} exists: review or remove it first")
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(pack, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(pack['criteria'])} criteria, {len(pack['documents'])} documents)")
    if not (KNOWLEDGE / args.portal / "_portal.json").exists():
        print(f"note: add knowledge/{args.portal}/_portal.json (portal name + url) when reviewing")


if __name__ == "__main__":
    main()
